version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: kongr-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_ERLANG_COOKIE: "RABBITMQ-KONGR-COOKIES"
      RABBITMQ_DEFAULT_USER: "kongr"
      RABBITMQ_DEFAULT_PASS: "kongr"