logging:
  level:
    root: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.hibernate.type.descriptor.sql: trace
  file:
    path: target/logs

server:
  port: 8080

spring:
  profiles:
    active: local
  jackson:
    default-property-inclusion: non_empty
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

#Local
---
spring:
  profiles: local
  cloud:
    function:
      definition: direct;broadcast
    stream:
      bindings:
        direct-out-0:
          destination: p2p-topic
        broadcast-out-0:
          destination: pubsub-topic
  rabbitmq:
    addresses: localhost
    username: kongr
    password: kongr


#Prod
---
spring:
  profiles: prod

logging:
  file:
    max-size: 100MB
    max-history: 30
    path: logs
  level:
    root: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    org.hibernate.type.descriptor.sql: INFO